### ISSUE TITLE
feat: implement analytics, error tracking and notifications

### ISSUE THREAD

**Issue by seangray-dev** [seangray-dev/somnyx#5]
- [ ] Set up PWA with notifications
- [ ] Emails (welcome, reminders, etc.)
- [ ] Integrate analytics using PostHog or Plausible
- [ ] Add error management via Sentry?
- [x] AI generated images for users dreams analyzed (not available without using credits)
